application: go-for-plivo
version: 2

runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- appstats: on

inbound_services:
- warmup
- channel_presence

default_expiration: "0s"
handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /js
  static_dir: static/js
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /html
  static_dir: static/html
- url: /.*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest